spring:
  cloud:
    config:
      uri: http://localhost:8888
      name: ${spring.application.name},kafka
      label: main
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        input:
          destination: input
          contentType: application/json
        output:
          destination: output
          contentType: application/json