spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        input:
          destination: input
          contentType: application/json
        output:
          destination: output
          contentType: application/json